const CONFIG = {
  MAX_NUM_CUSTOMERS: 6,
  HASH_SIZE: 64,
  GENDER_OPTIONS: ["MALE", "FEMALE", "UNINFORMED"],
  PRICE_OPTIONS: [50, 100, 300],
  PCR_RESULT_OPTIONS: ["POSITIVE", "NEGATIVE", "UNKNOWN"],
};

module.exports = { CONFIG };
